### ISSUE TITLE
Stroke misalignment in Chrome

### ISSUE THREAD

**Issue by melchiar** [googlefonts/italianno#7]
Love the font! There appears however to be an issue with this font's stroke alignment when drawing to canvas in Chrome (PC).

https://codepen.io/melchiar/pen/LYeKaow

Observe the stroke alignment in Chrome:

![image](https://user-images.githubusercontent.com/9057412/165401944-0290ddf2-3389-4b72-b987-3c122ae63cf4.png)

Compared with the same code in Firefox

![image](https://user-images.githubusercontent.com/9057412/165402100-e42e0e0b-ad53-4c0f-a465-d63c6df3f5ed.png)

Not sure if the issue is with Chrome or this font, but I have not been able to reproduce with any other fonts.

**Comment by vv-monsalve** [comment]
Hi @melchiar when opening the above link I can't reproduce the issue (macOS Big Sur, Chrome Version 107.0.5304.87)
Is this still happening to you?

**Comment by melchiar** [comment]
This seems to be resolved now, thank you
